output "codebuild_project" {
  description = "The CodeBuild project."
  value       = aws_codebuild_project.main
}

output "codebuild_project_arn" {
  description = "The CodeBuild project."
  value       = aws_codebuild_project.main.arn
}

output "codebuild_role" {
  description = "autogenerated role for codebuild"
  value       = aws_iam_role.codebuild
}

output "invoke_codebuild_role" {
  description = "autogenerated role for invoke codebuild"
  value       = aws_iam_role.invoke-codebuild
}
